### ISSUE TITLE
Tilføje muligheden for at slette runder (som blev oprettet ved en fejl)

### ISSUE THREAD

**Issue by valli28** [Crowdedlight/SifQuizManager#7]
Og måske også at ændre titlen på gamle runder...

**Comment by Crowdedlight** [comment]
Er tilføjet i 8f7751c 
Serveren er opdateret. 

Ved deletes kan jeg godt manuelt genskabe runden, men i vil ikke selv kunne se den på nogen måde i applikationen, da jeg skal manuelt ind i databasen og genskabe den.
